services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextgen_app
    volumes:
      - .:/var/www
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=${{RAILWAY_MYSQL_HOST:-mysql}}
      - DB_PORT=${{RAILWAY_MYSQL_PORT:-3306}}
      - DB_USERNAME=${{RAILWAY_MYSQL_USER:-root}}
      - DB_PASSWORD=${{RAILWAY_MYSQL_PASSWORD:-root}}
      - DB_DATABASE=${{RAILWAY_MYSQL_DATABASE:-NEXTGEN}}
    networks:
      - nextgen_network

  web:
    image: nginx:alpine
    container_name: nextgen_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - nextgen_network

  mysql:
    image: mysql:8.0
    container_name: nextgen_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${RAILWAY_MYSQL_PASSWORD:-root}
      MYSQL_DATABASE: ${RAILWAY_MYSQL_DATABASE:-NEXTGEN}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${RAILWAY_MYSQL_PASSWORD:-root}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nextgen_network

volumes:
  mysql_data:

networks:
  nextgen_network:
    driver: bridge